import React, { ReactNode } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/layouts/mainlayout.module.css'

const inter = Inter({ subsets: ['latin'] })

interface IProps {
  children?: ReactNode,
  isLoading?:boolean
  // any props that come into the component
}


export default function MainLayout({ children, ...props }:IProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.layoutContainer}>
        <div className={styles.header}>
          <div>Search PokeMon APP</div>
        </div>
        <div className={props.isLoading?styles.LoadingScreen:styles.hidden}>
          <div>Searching .... </div>
          <Image src='loading.svg' width="100" height="100" alt="Loading ..." />
        </div>
        <div className={styles.mainBody}>
        {children}
        </div>
       
      </main>
    </>
  )
}
